Tests for lms-subjects
hse-mtc/dal pull request #403
Opened 2021-11-03 07:44 UTC by beabinside

Added tests for /common/subjects/

2022-09-02 07:34 UTC, war-kolbus requested changes
Not so bad 4/5
You should also test same with permissions

2022-09-02 07:34 UTC, war-kolbus commented on back-end/src/common/tests/conftest.py
> +SUPERUSER_EMAIL = "superuserfortests@mail.com"
You should use only one conftest.py. Now there 2: tests/conftest.py and src/conftest.py. Pls merge this 2 files

2022-09-02 07:34 UTC, war-kolbus commented on back-end/src/common/tests/test_subjects.py
> +@pytest.mark.django_db
Move this func to common

2022-09-02 07:34 UTC, war-kolbus commented on back-end/src/common/tests/test_subjects.py
> +    subj_data = get_new_subject_data(title="Строевая подготовка 2")
You dont need it

2022-09-02 07:34 UTC, war-kolbus commented on back-end/src/common/tests/test_subjects.py
> +        print(subject)
You should get rid of "print"

2023-11-01 14:03 UTC, ShishckovA approved these changes

2023-11-01 14:17 UTC, merged