added milspecialities subject choose
hse-mtc/dal pull request #534
Opened 2023-02-17 09:24 UTC by RomanPrigorodov

2023-02-20 22:41 UTC, ShishckovA requested changes
Выглядит хорошо, кроме коммента после отправки "формы", которая на самом деле создание учебной дисциплины. 

Давай ещё в табличку добавим на http://51.250.94.20/apanel/subjects/ номер ВУСовки. В задачку пропишу
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/33600436/220208361-f57e4b0f-c309-4103-a364-443a2efccc7b.png">

2023-02-20 22:41 UTC, ShishckovA commented on front-end/src/components/Apanel/SubjectsControl.vue
> +            message: "Форма успешно отправлена!",
Почему форма?

2023-03-03 10:05 UTC, Danissimon approved these changes

2023-03-10 06:44 UTC, ShishckovA approved these changes

2023-03-10 06:44 UTC, merged