filter milspecialties for subjects
hse-mtc/dal pull request #539
Opened 2023-03-10 08:15 UTC by RomanPrigorodov

2023-03-10 09:10 UTC, ShishckovA requested changes

2023-03-23 23:29 UTC, ShishckovA requested changes
Не работает на проде, в карточке написал

И мастер подмёрж, там теперь в деве, например, есть для предметов есть указания на milspeciality, к которым они привязаны, может помочь

2023-03-24 08:56 UTC, ShishckovA commented
![telegram-cloud-photo-size-2-5255959545967134366-x](https://user-images.githubusercontent.com/33600436/227471908-790a48e2-c827-4e43-99b5-2fa3d91f5fcd.jpg)

2023-03-24 09:20 UTC, deborisov approved these changes

2023-03-24 09:32 UTC, ShishckovA approved these changes

2023-03-24 09:33 UTC, merged