Feature/error registration notification
hse-mtc/dal pull request #550
Opened 2023-04-07 08:46 UTC by RomanPrigorodov

2023-04-13 22:40 UTC, ShishckovA requested changes

2023-04-13 22:40 UTC, ShishckovA commented on back-end/src/lms/views/students.py
> +                },
Я бы лучше кидал ошибку с error_message что-то типа "email_already_exists", а на фронте обрабатывал её в более человекочитаемый формат. Но так, наверное, тоже ок

2023-04-13 22:40 UTC, ShishckovA commented on back-end/src/common/serializers/personal.py
> +
А то же самое для преподов?

Давайте раз уж фронт начали фиксить для них, то и бек в этом mr-е @Altius01

2023-04-13 22:55 UTC, ShishckovA commented on front-end/src/components/StudentRegistration/Student.vue
> +      const regExp = /^\+7?\d{10}$/;
Регулярка некорректная

На какие номера, кроме +71234567890 ты рассчитывал? На 1234567890? Тогда, видимо, "+7" надо взять в скобочки – сейчас у тебя обязательный плюс, но необязательная семёрка

2023-04-13 22:55 UTC, ShishckovA commented on back-end/src/lms/views/students.py
> +                },
@RomanPrigorodov

2023-04-13 22:59 UTC, ShishckovA commented on front-end/src/components/StudentRegistration/Student.vue
> +      const regExp = /^\+7?\d{10}$/;
@RomanPrigorodov

2023-06-28 13:34 UTC, deborisov submitted a review, later dismissed

2023-06-30 13:38 UTC, ShishckovA requested changes

2023-06-30 13:38 UTC, ShishckovA commented on front-end/src/components/TeacherRegistration/Teacher.vue
> +        }
Тут соответственно проверяем код возврата

2023-06-30 14:09 UTC, ShishckovA requested changes

2023-06-30 14:09 UTC, ShishckovA commented on front-end/src/components/StudentRegistration/Student.vue
> +        }
Тут соответственно проверяем код возврата

2023-06-30 14:42 UTC, ShishckovA approved these changes

2023-06-30 14:42 UTC, ShishckovA commented on back-end/src/lms/views/teachers.py
> +            )
А на самом деле можно просто error_message проверять

2023-06-30 14:44 UTC, merged