Feature/marks history
hse-mtc/dal pull request #577
Opened 2023-07-15 11:46 UTC by RomanPrigorodov

2023-07-18 08:43 UTC, ShishckovA commented
Надо добавить в отображение:
* Предмет, по которому было изменение оценки
* Дату, когда этот предмет был

При нажатии на кнопку "История изменения оценок":
* Фильтровать изменения по дате, когда этот предмет был (не по времени изменения оценки)
* Фильтровать по предмету, который выбран в плашке сверху

Давайте ещё добавим время изменения оценки с точностью до минуты

2023-07-18 08:43 UTC, ShishckovA requested changes

2023-07-18 08:43 UTC, ShishckovA commented on front-end/src/components/Marks/Marks.vue
> +      })
А по дате фильтровать будем? Там же есть календарик

2023-07-18 14:58 UTC, Altius01 commented on front-end/src/components/Marks/Marks.vue
> +      })
Уже фильтруем

2023-07-21 07:10 UTC, deborisov approved these changes

2023-10-31 18:36 UTC, merged