Add СНИЛС and ИНН
hse-mtc/dal pull request #599
Opened 2023-11-01 08:53 UTC by startsev2000

Added data for applicants

2023-11-01 11:12 UTC, ShishckovA requested changes

2023-11-01 11:12 UTC, ShishckovA commented on front-end/package-lock.json
> +      "integrity": "sha512-2v9fHL0ZGINotOlRIAJD5YuVB8V7WKxrE9Qy7dXhRipa035+kF7WuU/z+tEmLVPBcJ0zt8mOu1DKpWcVzBK8IA==",
Почему-то всё равно есть изменения =(

2023-11-01 11:12 UTC, ShishckovA commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
Это моделька для паспорта, сюда не норм вставлять ИНН и СНИЛС. 

Надо либо добавить новую модельку, либо переименовать в что-то типа PassportData

2023-11-01 11:12 UTC, ShishckovA commented on back-end/src/common/migrations/0004_auto_20231101_1140.py
> +            field=models.CharField(default='771234567890', max_length=13),
1. Ты сам редактировал файлик migrations? Это так себе практика
2. Дефолтное значение странное: если ИНН не указать, то он проставится в 771234567890?

2023-11-01 11:12 UTC, ShishckovA commented on front-end/src/constants/applicantForm.js
> +  tax_id: {
В `front-end/src/views/ApplicantForm/index.vue` стоит ещё валидаторы проставить для новых полей

2023-11-04 15:55 UTC, startsev2000 commented on back-end/src/common/migrations/0004_auto_20231101_1140.py
> +            field=models.CharField(default='771234567890', max_length=13),
Файл migrations не сам правил, он такой получился после команды docker-compose run back-end python manage.py makemigrations

2023-11-04 15:56 UTC, startsev2000 commented on back-end/src/common/migrations/0004_auto_20231101_1140.py
> +            field=models.CharField(default='771234567890', max_length=13),
Дефолтное значение да, странное. Можно поставить пустую строку

2023-11-04 15:57 UTC, startsev2000 commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
Есть смысл вынести добавление ИНН и СНИЛС в отдельную страницу в форме?
По мне так лучше просто переименовать в PassportData - по сути это всё информация о личных документах. Но можно и разделить, тут дело вкуса скорее)

2023-11-04 15:59 UTC, startsev2000 commented on front-end/package-lock.json
> +      "integrity": "sha512-2v9fHL0ZGINotOlRIAJD5YuVB8V7WKxrE9Qy7dXhRipa035+kF7WuU/z+tEmLVPBcJ0zt8mOu1DKpWcVzBK8IA==",
Надо всё-таки убедиться, генерируется ли каждый раз этот файл заново при запуске. Потому что если генерируется, то пусть меняется себе. Можно вообще его в гитигнор закинуть
P.S. у айоса есть файл Podfile.lock, он без проблем перегенерируется при каждом запуске. Думаю здесь также

2023-11-04 17:50 UTC, ShishckovA commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
В отдельной странице в форме смысла нет.

Не очень нравится название `PasswordData`, как будто оно только про паспорт =( Есть какой-то аналог словосочетания "паспортные данные" на английском, чтобы это обозначало более общую штуку, включая СНИЛС и ИНН? Типа `PersonalDocument(s)`?

После этого видимо снова придётся перегенерить миграцию, можешь стереть файлик `0004_auto_20231101_1140.py` и снова прописать `docker-compose run back-end python manage.py makemigrations`. 

Там, кстати, почему-то не прописалось нормальное название миграции, так что задай его вручную (к примеру, renamed_password_to_passworddata, как в [гайде](https://github.com/hse-mtc/dal/blob/master/back-end/docs/deployment.md) написано

2023-11-04 17:50 UTC, ShishckovA commented on back-end/src/common/migrations/0004_auto_20231101_1140.py
> +            field=models.CharField(default='771234567890', max_length=13),
> Можно поставить пустую строку

Да, думаю ок

2023-11-05 00:07 UTC, ShishckovA commented on front-end/package-lock.json
> +      "integrity": "sha512-2v9fHL0ZGINotOlRIAJD5YuVB8V7WKxrE9Qy7dXhRipa035+kF7WuU/z+tEmLVPBcJ0zt8mOu1DKpWcVzBK8IA==",
https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

`package-lock.json` используется для фиксирования зависимостей. Если его нет, устанавливаются какие-то версии пакетов из `package.json`. Если же есть `-lock` файл, то ставятся ровно те версии, которые в нём прописаны. Поэтому когда ты обновляешь `-lock` файл, вообще говоря неизвестна работоспособность сервиса на текущем сочетании minor-версий. Так что давай откатим этот `-lock`-файл.

А в корне он находится по ошибке, я его вытру

2023-11-15 13:08 UTC, ShishckovA requested changes

2023-11-15 13:08 UTC, ShishckovA commented on back-end/src/common/models/personal.py
>          verbose_name = "Passport"
По-хорошему если ты взялся переименовывать модельку, надо все соответсвующие поля переименовать. Туда же `back-end/src/common/serializers/personal.py:125` (`PassportSerializer`) `back-end/src/ams/models/applicants.py:136`, и в сериализаторах тоже (кроме, возможно, passport_handed_over, который именно про паспорт – принёс ли поступающий паспорт Жугиной). Поищи по коду

2023-11-15 13:53 UTC, TmLev commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
Лучше будет не мешать в кучу разные данные и сделать отдельные сущности под паспорт, СНИЛС, ИНН.
Всегда найдётся человек, у которого чего-то нет  ¯\_(ツ)_/¯

2023-11-22 06:53 UTC, startsev2000 commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
Но в таком смысле будет смысл вынести СНИЛС и ИНН на отдельную страницу
Надо будет уточнить по данному вопросу

2023-11-22 08:11 UTC, TmLev commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
Да как раз-таки не факт, спрашивать можно вместе

2023-11-22 08:27 UTC, startsev2000 commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
Тогда можно сделать так:
- оставить сущность по паспорту как было раньше
- добавить новую сущность под ИНН и СНИЛС
- при этом предлагать вводить ИНН и СНИЛС вместе с паспортными данными (при этом как необязательные данные, потому что может быть не у всех. Но этот момент в идеале бы уточнить)

Но может ли быть нюанс с тем, что если ИНН и СНИЛС выделять как отдельную сущность, то будут проблемы с тем, чтобы предлагать вводить эти данные на одной странице? В таком случае может всё-таки есть смысл предлагать вводить эти данные на отдельной странице?

2023-11-22 09:25 UTC, TmLev commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
А какие могут быть проблемы? В ручку приходят все данные, по порядку создаём сущности и привязываем к абитуриенту

2023-11-22 09:27 UTC, startsev2000 commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
Имею в виду - проблемы с реализацией на фронте (там насколько помню одна сущность - одна страница)

2023-11-22 09:37 UTC, TmLev commented on back-end/src/common/models/personal.py
> +    insurance_number = models.CharField(max_length=14)
Можно же подпилить фронт

2023-11-29 12:48 UTC, ShishckovA commented on back-end/src/ams/populate/applicants.py
> +            "patronymic_genitive": "Олçеговича",
_Vive la France_

2023-12-04 10:17 UTC, ShishckovA requested changes
Ты пробовал перезапускать накатывать миграции поверх данных? Там кажется всё затирается =(

2024-01-31 19:25 UTC, ShishckovA commented
@startsev2000 
Закрываем как неактуальный?

2024-01-31 19:43 UTC, startsev2000 commented
> @startsev2000 Закрываем как неактуальный?

Закрываем)

2024-01-31 19:45 UTC, closed without merging

2024-01-31 19:46 UTC, ShishckovA commented
Исправлено в #601