Add insure number, tax_id, passp in extended table
hse-mtc/dal pull request #603
Opened 2024-02-14 10:41 UTC by gsfatakhov

2024-03-09 01:34 UTC, ShishckovA requested changes
Выглядит окейно, заказчку показали? Скажет, что подправить

2024-03-09 01:34 UTC, ShishckovA commented on back-end/src/ams/utils/export/comp_sel_protocol.py
> +        row += [(phone, formats.table_center)]
Наверное можно `applicant.contact_info.personal_phone_number or ""`?

2024-03-09 01:34 UTC, ShishckovA commented on back-end/src/ams/utils/export/comp_sel_protocol.py
>      else:
Эта функция, и вообще всё что относится к детализированному протоколу, по-хорошему, должны быть в отдельном файлике (`export/detailed`?) Изначально баг не твой, но может перенесёшь?

2024-03-13 09:19 UTC, startsev2000 approved these changes
Работает - не трогай
Код теперь нормас

2024-03-13 10:39 UTC, startsev2000 approved these changes

2024-03-13 10:41 UTC, ShishckovA approved these changes
Угу, вроде ок

2024-03-13 10:41 UTC, merged