Applicant to student feature
hse-mtc/dal pull request #605
Opened 2024-02-21 06:56 UTC by startsev2000

2024-02-28 08:10 UTC, startsev2000 commented
Нужно при регистрации студента из абитуриента добавить больше данных для того, чтобы в регистрации студента была полноценная информация

2024-03-09 00:24 UTC, ShishckovA requested changes
Пока так, но нужно думать, как создавать студента, чтобы ContactInfo не дублировался

2024-03-09 00:24 UTC, ShishckovA commented on front-end/src/views/ApplicantsDocuments/index.vue
> +        email: item.email,
А это зачем?

2024-03-09 00:24 UTC, ShishckovA commented on front-end/src/components/ApplicantToStudent/index.vue
> +      type: [String, Number],
Так String или Number?

2024-03-09 07:19 UTC, startsev2000 commented on front-end/src/components/@ApplicantsDocuments/Table.vue
> +        </a>
Эт пока тестовая фича (можно сказать, не баг, а фича). Хотим понять, нормально ли регаются студенты сами по ссылке сами. Если нет, то сделаем кнопку (скорее всего в самой дальней части таблицы, она всё-таки редко используется)

2024-03-09 07:21 UTC, startsev2000 commented on front-end/src/components/ApplicantToStudent/Student.vue
> +    delete data.family;
Эту штуку возможно пофиксит как раз нормальный перевод в студента. При регистрации с фулл датой через обычный метод кидало ошибку на то, что фотка не норм, и какие-то данные в семье пропущены. Есть вероятность того, что если конвертацию сделать по-другому - будет норм

+ на фотку можно забить - очень многие заливают фотки ещё и с не совсем корректным внешним видом, поэтому как будто есть смысл для студентов заливать уже новые с норм видом и даже в форме

2024-03-09 07:21 UTC, startsev2000 commented on front-end/src/views/ApplicantsDocuments/index.vue
> +        email: item.email,
Тоже задумался

2024-03-09 07:22 UTC, startsev2000 commented on front-end/src/components/ApplicantToStudent/index.vue
> +      type: [String, Number],
Определюсь
Всё время делема, а какого же типа айдишник) поэтому перестраховался

2024-03-09 22:47 UTC, ShishckovA commented on front-end/src/components/ApplicantToStudent/Student.vue
> +    delete data.family;
> очень многие заливают фотки ещё и с не совсем корректным внешним видом

Это будет повод её поменять)
Заставить человека поменять фотографию легче, чем добавить новую

2024-04-03 13:40 UTC, gsfatakhov submitted a review, later dismissed

2024-09-08 10:21 UTC, ShishckovA commented on back-end/src/lms/views/students.py
> +    @action(detail=False, methods=["post"], permission_classes=[permissions.AllowAny])
[permissions.AllowAny] разве не значит, что я смогу дёргать эту ручку без авторизации вообще? Для /register так конечно и надо, а вот для register_from_applicant кажется суперплохо

2024-09-08 10:29 UTC, ShishckovA commented on back-end/src/lms/views/students.py
> +    @action(detail=False, methods=["post"], permission_classes=[permissions.AllowAny])
`Permissions.AllowAny` разве не значит, что я смогу дёргать эту ручку без авторизации вообще? Для `/register` так конечно и надо, а вот для register_from_applicant кажется суперплохо

2024-09-08 10:29 UTC, ShishckovA commented on back-end/src/lms/models/students.py
> +        blank=True,
Зачем? У нас есть аппликанты без contact info? При переходе в студенты же это обязательно должно быть заполнено

2024-09-08 10:29 UTC, ShishckovA commented on back-end/src/lms/views/students.py
> +        return Response(self.get_serializer(student).data)
TODO удалять модельку аппликанта? Это нужно?

2024-09-08 10:29 UTC, ShishckovA commented on back-end/src/ams/models/applicants.py
> +        blank=True,
А тут зачем?) Модельки contact info же не удаляются

2024-09-08 10:29 UTC, ShishckovA commented on back-end/src/ams/models/applicants.py
> +        blank=True,
Тоже непонятно, когда юзеры могут быть null?

2024-09-08 10:33 UTC, startsev2000 commented on back-end/src/lms/views/students.py
> +    @action(detail=False, methods=["post"], permission_classes=[permissions.AllowAny])
Логично, поставил `permissions.IsAdminUser`

2024-09-08 11:32 UTC, startsev2000 commented on back-end/src/lms/views/students.py
> +        return Response(self.get_serializer(student).data)
Теперь модельку аппликанта тоже удаляем вместе со студентом (если, конечно, аппликант у студента есть)

2024-09-08 11:32 UTC, startsev2000 commented on back-end/src/lms/models/students.py
> +        blank=True,
Reverted

2024-09-08 11:32 UTC, startsev2000 commented on back-end/src/ams/models/applicants.py
> +        blank=True,
Reverted

2024-09-08 11:32 UTC, startsev2000 commented on back-end/src/ams/models/applicants.py
> +        blank=True,
Reverted

2024-09-08 12:02 UTC, ShishckovA approved these changes

2024-09-19 08:24 UTC, merged