applicants-registration-endpoint
hse-mtc/dal pull request #606
Opened 2024-03-11 22:06 UTC by gsfatakhov

2024-03-12 07:30 UTC, startsev2000 requested changes
И пока не очень понятно, а какой у этой прекрасной ручки будет путь? 
А в остальном, если поправить два момента с получением данных с фронта, должно отработать

2024-03-12 07:30 UTC, startsev2000 commented on back-end/src/lms/views/students.py
> +        user_id = serializer.validated_data["user"]["id"]
Надо тестить. В модели есть просто поле `user` (по крайней мере так оно приходит на фронт) - это и есть айдишник юзера (который именно юзера, не аппликанта или студента)

И с контакт инфо надо тоже посмотреть, но тут кажется проще

2024-03-12 07:30 UTC, startsev2000 commented on back-end/src/lms/views/students.py
> +        contact_info = ContactInfo.objects.filter(id=contact_info_id)
А, точно. Можно же просто искать объект контакт инфо не по его айдишнику, а по корпоративной почте (по сути же будет один и тот же инстанс контакт инфо). Потому что пока не супер понятно, откуда можно взять айдишник - на фронте его не видел. А корп. почту видел)

2024-04-03 13:41 UTC, gsfatakhov commented
Продолжение в https://github.com/hse-mtc/dal/pull/605

2024-04-03 13:41 UTC, closed without merging