Add student number to table, sort rooms
hse-mtc/dal pull request #616
Opened 2024-09-20 10:28 UTC by startsev2000

2024-09-20 15:00 UTC, ShishckovA requested changes

2024-09-20 15:00 UTC, ShishckovA commented on front-end/src/components/Personnel/Students/Students.vue
> +        </PrimeColumn>
Давайте подумаем, как это можно красивее сделать. Мб выделить колонку цветом (может более блёкло?), сделать нумерацию всех челов всегда подряд.

А может и вообще отказаться и писать количество сверху

2024-09-20 15:00 UTC, ShishckovA commented on front-end/src/components/Personnel/Students/Students.vue
> +        :sort-field="fullname"
Я бы сказал что сначала по взводу, потом по фио, нет?

2024-09-20 15:00 UTC, ShishckovA commented on front-end/src/store/modules/reference.js
> +        data.sort((a, b) => a - b);
a, b – объекты, а не числа

2024-09-27 06:46 UTC, startsev2000 commented on front-end/src/store/modules/reference.js
> +        data.sort((a, b) => a - b);
Получилось исправить

2024-09-27 06:54 UTC, startsev2000 commented on front-end/src/components/Personnel/Students/Students.vue
> +        </PrimeColumn>
Ну смотри, отказаться точно нет - заказчик захотел так. Я сторонник того, что если заказчик хочет и то, что он хочет - не треш, то надо делать. Писать количество сверху - да, можно, но как будто бы страница выглядит нормально и не перегружено, перегружать не хочется от слова совсем.

"сделать нумерацию всех челов всегда подряд" - это я тоже хотел сделать, но чот не получилось. Ещё пробую. Делать блекло не вижу смысла, в других местах эта колонка не блеклая и всё хорошо

2024-09-27 06:56 UTC, startsev2000 commented on front-end/src/components/Personnel/Students/Students.vue
> +        :sort-field="fullname"
Если пофикшу коммент выше, то откачу

2024-09-27 09:01 UTC, ShishckovA commented on front-end/src/store/modules/reference.js
> +          if (titleA > titleB) { return 1; }
А зачем эти две строчки, если localeCompare делает то же самое?

2024-09-27 09:05 UTC, ShishckovA approved these changes

2024-09-27 09:07 UTC, merged